export const SCENARIOS = {
  project_catalog_single: {
    id: "project_catalog_single",
    projectCatalog: {
      daemon_context: {
        reachability_state: "reachable",
        auth_status: "valid",
        daemon_app_name: "AI Coding Daemon",
        daemon_version: "0.1.0",
        authority: "daemon",
        session_backend: "fake",
      },
      projects: [
        {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
          bootstrap_ready: true,
          readiness_code: "ready",
          readiness_message: null,
          default_branch: "main",
          head_commit_sha: "abc1234def56",
        },
      ],
    },
    nodeKinds: {
      definitions: [
        {
          kind: "epic",
          tier: "epic",
          description: "Epic node",
          allow_parentless: true,
          allowed_parent_kinds: [],
          allowed_child_kinds: ["phase"],
        },
      ],
      top_level_kinds: ["epic"],
    },
    topLevelCreateResponseByProjectId: {
      repo_alpha: {
        status: "started",
        requested_start_run: true,
        resolved_title: "Website UI bootstrap",
        project: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        source_repo: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        bootstrap: {
          repo_bootstrap_status: "bootstrapped",
          worker_repo_path: "/mock-runtime/git/node_versions/node-version-root",
          branch_name: "tier/epic/epic/website-ui-bootstrap__node-root/v1",
          seed_commit_sha: "abc1234",
          head_commit_sha: "abc1234",
          working_tree_state: "seed_ready",
        },
        node: {
          node_id: "node-root",
          parent_node_id: null,
          kind: "epic",
          tier: "epic",
          title: "Website UI bootstrap",
          prompt: "Create the initial website UI workflow.",
          created_via: "manual",
        },
        node_version_id: "node-version-root",
        compile: {
          status: "compiled",
          node_version_id: "node-version-root",
          logical_node_id: "node-root",
          compile_context: {},
        },
        lifecycle: {
          node_id: "node-root",
          lifecycle_state: "RUNNING",
          run_status: "RUNNING",
          current_run_id: "run-root",
          current_task_id: null,
          current_subtask_id: null,
          current_subtask_attempt: null,
          last_completed_subtask_id: null,
          execution_cursor_json: {},
          failure_count_from_children: 0,
          failure_count_consecutive: 0,
          defer_to_user_threshold: 0,
          is_resumable: false,
          pause_flag_name: null,
          working_tree_state: null,
          updated_at: "2026-03-11T00:00:00Z",
        },
        run_admission: {
          status: "admitted",
          node_id: "node-root",
          node_run_id: "run-root",
          trigger_reason: "workflow_start",
        },
        run_progress: {
          node_id: "node-root",
          run: {
            id: "run-root",
            logical_node_id: "node-root",
            trigger_reason: "workflow_start",
          },
          current_subtask: null,
          current_attempt: null,
        },
        route_hint: {
          project_id: "repo_alpha",
          node_id: "node-root",
          tab: "overview",
          url: "/projects/repo_alpha/nodes/node-root/overview",
        },
      },
    },
    projectBootstrapByProjectId: {
      repo_alpha: {
        project: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        root_node_id: null,
        route_hint: null,
      },
    },
    treeByNodeId: {
      "node-root": {
        root_node_id: "node-root",
        generated_at: "2026-03-11T00:00:00Z",
        nodes: [
          {
            node_id: "node-root",
            parent_node_id: null,
            depth: 0,
            kind: "epic",
            tier: "epic",
            title: "Website UI bootstrap",
            authoritative_node_version_id: "node-version-root",
            latest_created_node_version_id: "node-version-root",
            lifecycle_state: "READY",
            run_status: "RUNNING",
            scheduling_status: "already_running",
            blocker_count: 0,
            blocker_state: "none",
            has_children: true,
            child_count: 1,
            child_rollups: {
              total: 1,
              ready: 0,
              running: 0,
              paused_for_user: 0,
              blocked: 0,
              failed: 0,
              complete: 1,
              superseded: 0,
              not_compiled: 0,
            },
            created_at: "2026-03-11T00:00:00Z",
            last_updated_at: "2026-03-11T00:00:00Z",
          },
          {
            node_id: "node-task-1",
            parent_node_id: "node-root",
            depth: 1,
            kind: "task",
            tier: "task",
            title: "Bootstrap React shell",
            authoritative_node_version_id: "node-version-task-1",
            latest_created_node_version_id: "node-version-task-1",
            lifecycle_state: "COMPLETE",
            run_status: "COMPLETE",
            scheduling_status: "complete",
            blocker_count: 0,
            blocker_state: "none",
            has_children: false,
            child_count: 0,
            child_rollups: {
              total: 0,
              ready: 0,
              running: 0,
              paused_for_user: 0,
              blocked: 0,
              failed: 0,
              complete: 0,
              superseded: 0,
              not_compiled: 0,
            },
            created_at: "2026-03-11T00:00:00Z",
            last_updated_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
    },
    nodeSummaryByNodeId: {
      "node-root": {
        node_id: "node-root",
        parent_node_id: null,
        kind: "epic",
        tier: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow.",
        created_via: "manual",
        lifecycle_state: "READY",
        run_status: "RUNNING",
        current_run_id: "run-root",
        current_subtask_id: "subtask-root",
        current_subtask_attempt: 1,
        pause_flag_name: null,
        is_resumable: false,
        authoritative_node_version_id: "node-version-root",
        latest_created_node_version_id: "node-version-root",
        compiled_workflow_id: "workflow-root",
        active_branch_name: "node-root-v1",
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-task-1": {
        node_id: "node-task-1",
        parent_node_id: "node-root",
        kind: "task",
        tier: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell.",
        created_via: "manual",
        lifecycle_state: "COMPLETE",
        run_status: "COMPLETE",
        current_run_id: "run-task-1",
        current_subtask_id: null,
        current_subtask_attempt: null,
        pause_flag_name: null,
        is_resumable: false,
        authoritative_node_version_id: "node-version-task-1",
        latest_created_node_version_id: "node-version-task-1",
        compiled_workflow_id: "workflow-task-1",
        active_branch_name: "node-task-1-v1",
        seed_commit_sha: "def456",
        final_commit_sha: "fedcba",
      },
    },
    nodeLineageByNodeId: {
      "node-root": {
        logical_node_id: "node-root",
        authoritative_node_version_id: "node-version-root",
        latest_created_node_version_id: "node-version-root",
        versions: [{ id: "node-version-root" }],
      },
      "node-task-1": {
        logical_node_id: "node-task-1",
        authoritative_node_version_id: "node-version-task-1",
        latest_created_node_version_id: "node-version-task-1",
        versions: [{ id: "node-version-task-1" }],
      },
    },
    nodeVersionById: {
      "node-version-root": {
        id: "node-version-root",
        logical_node_id: "node-root",
        parent_node_version_id: null,
        tier: "epic",
        node_kind: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow.",
        description: null,
        status: "authoritative",
        version_number: 1,
        compiled_workflow_id: "workflow-root",
        supersedes_node_version_id: null,
        active_branch_name: "node-root-v1",
        branch_generation_number: 1,
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-version-task-1": {
        id: "node-version-task-1",
        logical_node_id: "node-task-1",
        parent_node_version_id: "node-version-root",
        tier: "task",
        node_kind: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell.",
        description: null,
        status: "authoritative",
        version_number: 1,
        compiled_workflow_id: "workflow-task-1",
        supersedes_node_version_id: null,
        active_branch_name: "node-task-1-v1",
        branch_generation_number: 1,
        seed_commit_sha: "def456",
        final_commit_sha: "fedcba",
      },
    },
    promptHistoryByNodeId: {
      "node-root": {
        node_id: "node-root",
        prompts: [
          {
            id: "prompt-root-1",
            node_version_id: "node-version-root",
            node_run_id: "run-root",
            compiled_subtask_id: "subtask-root",
            prompt_role: "execution",
            source_subtask_key: "research_context",
            template_path: "prompts/root.md",
            template_hash: "hash-root-prompt",
            content: "Investigate the website operator shell requirements.",
            content_hash: "hash-root-prompt-content",
            payload_json: {},
            delivered_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
      "node-task-1": {
        node_id: "node-task-1",
        prompts: [
          {
            id: "prompt-task-1",
            node_version_id: "node-version-task-1",
            node_run_id: "run-task-1",
            compiled_subtask_id: "subtask-task-1",
            prompt_role: "execution",
            source_subtask_key: "execute_node",
            template_path: "prompts/task.md",
            template_hash: "hash-task-prompt",
            content: "Build the first React shell for the operator website.",
            content_hash: "hash-task-prompt-content",
            payload_json: {},
            delivered_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
    },
    supersedeTemplateByNodeId: {
      "node-root": {
        id: "node-version-root-v2",
        logical_node_id: "node-root",
        parent_node_version_id: null,
        tier: "epic",
        node_kind: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow with stronger prompt review.",
        description: null,
        status: "candidate",
        version_number: 2,
        compiled_workflow_id: null,
        supersedes_node_version_id: "node-version-root",
        active_branch_name: "node-root-v2",
        branch_generation_number: 2,
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-task-1": {
        id: "node-version-task-1-v2",
        logical_node_id: "node-task-1",
        parent_node_version_id: "node-version-root",
        tier: "task",
        node_kind: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell with a real routed detail layout.",
        description: null,
        status: "candidate",
        version_number: 2,
        compiled_workflow_id: null,
        supersedes_node_version_id: "node-version-task-1",
        active_branch_name: "node-task-1-v2",
        branch_generation_number: 2,
        seed_commit_sha: "def456",
        final_commit_sha: null,
      },
    },
    regenerateResponseByNodeId: {
      "node-root": {
        root_node_id: "node-root",
        root_node_version_id: "node-version-root-v2",
        scope: "subtree",
        trigger_reason: "manual_regenerate",
        created_candidate_version_ids: ["node-version-root-v2"],
        stable_candidate_version_ids: ["node-version-root-v2"],
        rebuild_history: [],
      },
      "node-task-1": {
        root_node_id: "node-task-1",
        root_node_version_id: "node-version-task-1-v2",
        scope: "subtree",
        trigger_reason: "manual_regenerate",
        created_candidate_version_ids: ["node-version-task-1-v2"],
        stable_candidate_version_ids: ["node-version-task-1-v2"],
        rebuild_history: [],
      },
    },
    workflowByNodeId: {
      "node-root": {
        id: "workflow-root",
        node_version_id: "node-version-root",
        logical_node_id: "node-root",
        source_hash: "hash-root",
        built_in_library_version: "test",
        created_at: "2026-03-11T00:00:00Z",
        source_document_count: 4,
        task_count: 2,
        subtask_count: 3,
        compile_context: {},
        resolved_yaml: {},
        tasks: [
          { id: "task-a", task_key: "research_context", ordinal: 1, title: "Research", description: null, config_json: {}, subtasks: [{ id: "subtask-a1" }] },
          { id: "task-b", task_key: "execute_node", ordinal: 2, title: "Execute", description: null, config_json: {}, subtasks: [{ id: "subtask-b1" }, { id: "subtask-b2" }] },
        ],
      },
      "node-task-1": {
        id: "workflow-task-1",
        node_version_id: "node-version-task-1",
        logical_node_id: "node-task-1",
        source_hash: "hash-task-1",
        built_in_library_version: "test",
        created_at: "2026-03-11T00:00:00Z",
        source_document_count: 3,
        task_count: 1,
        subtask_count: 1,
        compile_context: {},
        resolved_yaml: {},
        tasks: [{ id: "task-x", task_key: "execute_node", ordinal: 1, title: "Execute", description: null, config_json: {}, subtasks: [{ id: "subtask-x1" }] }],
      },
    },
    runProgressByNodeId: {
      "node-root": {
        node_id: "node-root",
        run: { id: "run-root", trigger_reason: "workflow_start" },
        current_subtask: { compiled_subtask_id: "subtask-root" },
        current_attempt: { attempt_number: 1 },
      },
      "node-task-1": {
        node_id: "node-task-1",
        run: { id: "run-task-1", trigger_reason: "workflow_start" },
        current_subtask: null,
        current_attempt: null,
      },
    },
    currentSubtaskByNodeId: {
      "node-root": {
        run: {
          id: "run-root",
          logical_node_id: "node-root",
          node_version_id: "node-version-root",
          trigger_reason: "workflow_start",
          run_status: "RUNNING",
          started_at: "2026-03-11T00:00:00Z",
          finished_at: null,
        },
        state: {
          node_run_id: "run-root",
          lifecycle_state: "RUNNING",
          current_task_id: "task-b",
          current_compiled_subtask_id: "subtask-b1",
          current_subtask_attempt: 2,
          last_completed_compiled_subtask_id: "subtask-a1",
          execution_cursor_json: { current_task_ordinal: 2, current_subtask_ordinal: 1 },
          failure_count_from_children: 0,
          failure_count_consecutive: 0,
          defer_to_user_threshold: null,
          pause_flag_name: null,
          is_resumable: false,
          working_tree_state: "clean",
          updated_at: "2026-03-11T00:05:00Z",
        },
        current_subtask: {
          id: "subtask-b1",
          compiled_task_id: "task-b",
          source_subtask_key: "execute_node.run_leaf_prompt",
          ordinal: 1,
          subtask_type: "execute_node",
          title: "Run implementation prompt",
          prompt_text: "Implement the next website operator shell slice and record what changed.",
          command_text: "npm run test:unit",
          environment_policy_ref: "environments/local_default.yaml",
          environment_request_json: {
            policy_id: "local_default",
            isolation_mode: "none",
            allow_network: true,
            runtime_profile: null,
            mandatory: false,
          },
          retry_policy_json: {
            max_attempts: 2,
            rerun_failed_only: false,
          },
          block_on_user_flag: null,
          pause_summary_prompt: null,
          source_file_path: "builtin/subtasks/execute_node.yaml",
          source_hash: "hash-subtask-b1",
          inserted_by_hook: false,
          inserted_by_hook_id: null,
          depends_on_compiled_subtask_ids: ["subtask-a1"],
        },
        latest_attempt: {
          id: "attempt-root-2",
          node_run_id: "run-root",
          compiled_subtask_id: "subtask-b1",
          attempt_number: 2,
          status: "RUNNING",
          input_context_json: {
            compiled_subtask_id: "subtask-b1",
            stage_context_json: { stage: { compiled_subtask_id: "subtask-b1", task_key: "execute_node" } },
          },
          output_json: {
            last_heartbeat_at: "2026-03-11T00:05:00Z",
            progress_message: "Applying routing changes to the website shell.",
          },
          execution_result_json: null,
          execution_environment_json: {
            launch_status: "active",
            resolved_mode: "none",
          },
          validation_json: null,
          review_json: null,
          testing_json: null,
          summary: null,
          started_at: "2026-03-11T00:04:30Z",
          ended_at: null,
        },
      },
    },
    currentSubtaskPromptByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_run_id: "run-root",
        compiled_subtask_id: "subtask-b1",
        prompt_id: "prompt-root-1",
        source_subtask_key: "execute_node.run_leaf_prompt",
        title: "Run implementation prompt",
        subtask_type: "execute_node",
        prompt_text: "Implement the next website operator shell slice and record what changed.",
        command_text: "npm run test:unit",
        environment_request_json: {
          policy_id: "local_default",
          isolation_mode: "none",
          allow_network: true,
          runtime_profile: null,
          mandatory: false,
        },
        stage_context_json: {
          startup: {
            node_id: "node-root",
            node_prompt: "Create the initial website UI workflow.",
          },
          stage: {
            compiled_subtask_id: "subtask-b1",
            task_key: "execute_node",
          },
        },
      },
    },
    currentSubtaskContextByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_run_id: "run-root",
        compiled_subtask_id: "subtask-b1",
        attempt_number: 2,
        input_context_json: {
          compiled_subtask_id: "subtask-b1",
          stage_context_json: {
            stage: {
              compiled_subtask_id: "subtask-b1",
              task_key: "execute_node",
            },
          },
          prior_results: [
            {
              compiled_subtask_id: "subtask-a1",
              summary: "Reviewed the current website shell structure.",
            },
          ],
        },
        latest_summary: "Reviewed the current website shell structure.",
        stage_context_json: {
          startup: {
            node_id: "node-root",
            node_prompt: "Create the initial website UI workflow.",
          },
          stage: {
            compiled_subtask_id: "subtask-b1",
            task_key: "execute_node",
          },
        },
      },
    },
    subtaskAttemptsByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_run_id: "run-root",
        attempts: [
          {
            id: "attempt-root-2",
            node_run_id: "run-root",
            compiled_subtask_id: "subtask-b1",
            attempt_number: 2,
            status: "RUNNING",
            input_context_json: {
              compiled_subtask_id: "subtask-b1",
            },
            output_json: {
              last_heartbeat_at: "2026-03-11T00:05:00Z",
            },
            execution_result_json: null,
            execution_environment_json: {
              launch_status: "active",
              resolved_mode: "none",
            },
            validation_json: null,
            review_json: null,
            testing_json: null,
            summary: null,
            started_at: "2026-03-11T00:04:30Z",
            ended_at: null,
          },
          {
            id: "attempt-root-1",
            node_run_id: "run-root",
            compiled_subtask_id: "subtask-a1",
            attempt_number: 1,
            status: "COMPLETE",
            input_context_json: {
              compiled_subtask_id: "subtask-a1",
            },
            output_json: {
              files_touched: 2,
            },
            execution_result_json: {
              exit_code: 0,
              stdout: "research complete",
            },
            execution_environment_json: {
              launch_status: "active",
              resolved_mode: "none",
            },
            validation_json: null,
            review_json: null,
            testing_json: null,
            summary: "Reviewed the current website shell structure.",
            started_at: "2026-03-11T00:01:00Z",
            ended_at: "2026-03-11T00:03:00Z",
          },
        ],
      },
    },
    subtaskAttemptById: {
      "attempt-root-1": {
        id: "attempt-root-1",
        node_run_id: "run-root",
        compiled_subtask_id: "subtask-a1",
        attempt_number: 1,
        status: "COMPLETE",
        input_context_json: {
          compiled_subtask_id: "subtask-a1",
        },
        output_json: {
          files_touched: 2,
        },
        execution_result_json: {
          exit_code: 0,
          stdout: "research complete",
        },
        execution_environment_json: {
          launch_status: "active",
          resolved_mode: "none",
        },
        validation_json: null,
        review_json: null,
        testing_json: null,
        summary: "Reviewed the current website shell structure.",
        started_at: "2026-03-11T00:01:00Z",
        ended_at: "2026-03-11T00:03:00Z",
      },
      "attempt-root-2": {
        id: "attempt-root-2",
        node_run_id: "run-root",
        compiled_subtask_id: "subtask-b1",
        attempt_number: 2,
        status: "RUNNING",
        input_context_json: {
          compiled_subtask_id: "subtask-b1",
          stage_context_json: { stage: { compiled_subtask_id: "subtask-b1", task_key: "execute_node" } },
        },
        output_json: {
          last_heartbeat_at: "2026-03-11T00:05:00Z",
          progress_message: "Applying routing changes to the website shell.",
        },
        execution_result_json: null,
        execution_environment_json: {
          launch_status: "active",
          resolved_mode: "none",
        },
        validation_json: null,
        review_json: null,
        testing_json: null,
        summary: null,
        started_at: "2026-03-11T00:04:30Z",
        ended_at: null,
      },
    },
    runsByNodeId: {
      "node-root": {
        node_id: "node-root",
        runs: [{ id: "run-root", status: "RUNNING", trigger_reason: "workflow_start" }],
      },
      "node-task-1": {
        node_id: "node-task-1",
        runs: [{ id: "run-task-1", status: "COMPLETE", trigger_reason: "workflow_start" }],
      },
    },
    summariesByNodeId: {
      "node-root": {
        node_id: "node-root",
        summaries: [{ id: "summary-root", summary_type: "operator", summary_scope: "node", created_at: "2026-03-11T00:00:00Z" }],
      },
      "node-task-1": {
        node_id: "node-task-1",
        summaries: [{ id: "summary-task-1", summary_type: "operator", summary_scope: "node", created_at: "2026-03-11T00:00:00Z" }],
      },
    },
    sessionsByNodeId: {
      "node-root": {
        node_id: "node-root",
        sessions: [{ session_id: "session-root", status: "running", provider: "codex", session_role: "primary", backend: "tmux" }],
      },
      "node-task-1": {
        node_id: "node-task-1",
        sessions: [],
      },
    },
    sourcesByNodeId: {
      "node-root": {
        node_version_id: "node-version-root",
        logical_node_id: "node-root",
        source_documents: [{ id: "source-root", relative_path: "nodes/epic.yaml", source_role: "base_definition" }],
      },
      "node-task-1": {
        node_version_id: "node-version-task-1",
        logical_node_id: "node-task-1",
        source_documents: [{ id: "source-task-1", relative_path: "nodes/task.yaml", source_role: "base_definition" }],
      },
    },
    rationaleByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_version_id: "node-version-root",
        prompt_record_id: null,
        summary_record_id: null,
        rationale_summary: "Root node establishes the website UI workstream.",
        change_counts: { added: 3, modified: 1 },
        entity_history: [],
      },
      "node-task-1": {
        node_id: "node-task-1",
        node_version_id: "node-version-task-1",
        prompt_record_id: null,
        summary_record_id: null,
        rationale_summary: "Task node built the initial React shell.",
        change_counts: { added: 2, modified: 4 },
        entity_history: [],
      },
    },
    actionCatalogByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_version_id: "node-version-root",
        actions: [
          { action_id: "pause_run", label: "Pause Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} },
          { action_id: "regenerate_node", label: "Regenerate Node", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "regenerate node", target_scope: "selected_node", details_json: {} },
        ],
      },
      "node-task-1": {
        node_id: "node-task-1",
        node_version_id: "node-version-task-1",
        actions: [
          { action_id: "start_run", label: "Start Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "start run", target_scope: "selected_node", details_json: {} },
          { action_id: "pause_run", label: "Pause Run", group: "execution", legal: false, blocked_reason: "node is not currently running", confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} },
          { action_id: "regenerate_node", label: "Regenerate Node", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "regenerate node", target_scope: "selected_node", details_json: {} },
        ],
      },
    },
  },
  healthy_tree_small: {
    id: "healthy_tree_small",
    projectCatalog: {
      daemon_context: {
        reachability_state: "reachable",
        auth_status: "valid",
        daemon_app_name: "AI Coding Daemon",
        daemon_version: "0.1.0",
        authority: "daemon",
        session_backend: "fake",
      },
      projects: [
        {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
          bootstrap_ready: true,
          readiness_code: "ready",
          readiness_message: null,
          default_branch: "main",
          head_commit_sha: "abc1234def56",
        },
      ],
    },
    nodeKinds: {
      definitions: [
        {
          kind: "epic",
          tier: "epic",
          description: "Epic node",
          allow_parentless: true,
          allowed_parent_kinds: [],
          allowed_child_kinds: ["phase"],
        },
        {
          kind: "task",
          tier: "task",
          description: "Task node",
          allow_parentless: true,
          allowed_parent_kinds: [],
          allowed_child_kinds: [],
        },
      ],
      top_level_kinds: ["epic", "task"],
    },
    topLevelCreateResponseByProjectId: {
      repo_alpha: {
        status: "started",
        requested_start_run: true,
        resolved_title: "Website UI bootstrap",
        project: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        source_repo: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        bootstrap: {
          repo_bootstrap_status: "bootstrapped",
          worker_repo_path: "/mock-runtime/git/node_versions/node-version-root",
          branch_name: "tier/epic/epic/website-ui-bootstrap__node-root/v1",
          seed_commit_sha: "abc1234",
          head_commit_sha: "abc1234",
          working_tree_state: "seed_ready",
        },
        node: {
          node_id: "node-root",
          parent_node_id: null,
          kind: "epic",
          tier: "epic",
          title: "Website UI bootstrap",
          prompt: "Create the initial website UI workflow.",
          created_via: "manual",
        },
        node_version_id: "node-version-root",
        compile: {
          status: "compiled",
          node_version_id: "node-version-root",
          logical_node_id: "node-root",
          compile_context: {},
        },
        lifecycle: {
          node_id: "node-root",
          lifecycle_state: "RUNNING",
          run_status: "RUNNING",
          current_run_id: "run-root",
          current_task_id: null,
          current_subtask_id: null,
          current_subtask_attempt: null,
          last_completed_subtask_id: null,
          execution_cursor_json: {},
          failure_count_from_children: 0,
          failure_count_consecutive: 0,
          defer_to_user_threshold: 0,
          is_resumable: false,
          pause_flag_name: null,
          working_tree_state: null,
          updated_at: "2026-03-11T00:00:00Z",
        },
        run_admission: {
          status: "admitted",
          node_id: "node-root",
          node_run_id: "run-root",
          trigger_reason: "workflow_start",
        },
        run_progress: {
          node_id: "node-root",
          run: {
            id: "run-root",
            logical_node_id: "node-root",
            trigger_reason: "workflow_start",
          },
          current_subtask: null,
          current_attempt: null,
        },
        route_hint: {
          project_id: "repo_alpha",
          node_id: "node-root",
          tab: "overview",
          url: "/projects/repo_alpha/nodes/node-root/overview",
        },
      },
    },
    projectBootstrapByProjectId: {
      repo_alpha: {
        project: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        root_node_id: "node-root",
        route_hint: {
          project_id: "repo_alpha",
          node_id: "node-root",
          tab: "overview",
          url: "/projects/repo_alpha/nodes/node-root/overview",
        },
      },
    },
    treeByNodeId: {
      "node-root": {
        root_node_id: "node-root",
        generated_at: "2026-03-11T00:00:00Z",
        nodes: [
          {
            node_id: "node-root",
            parent_node_id: null,
            depth: 0,
            kind: "epic",
            tier: "epic",
            title: "Website UI bootstrap",
            authoritative_node_version_id: "node-version-root",
            latest_created_node_version_id: "node-version-root",
            lifecycle_state: "READY",
            run_status: "RUNNING",
            scheduling_status: "already_running",
            blocker_count: 0,
            blocker_state: "none",
            has_children: true,
            child_count: 1,
            child_rollups: {
              total: 1,
              ready: 0,
              running: 0,
              paused_for_user: 0,
              blocked: 0,
              failed: 0,
              complete: 1,
              superseded: 0,
              not_compiled: 0,
            },
            created_at: "2026-03-11T00:00:00Z",
            last_updated_at: "2026-03-11T00:00:00Z",
          },
          {
            node_id: "node-task-1",
            parent_node_id: "node-root",
            depth: 1,
            kind: "task",
            tier: "task",
            title: "Bootstrap React shell",
            authoritative_node_version_id: "node-version-task-1",
            latest_created_node_version_id: "node-version-task-1",
            lifecycle_state: "COMPLETE",
            run_status: "COMPLETE",
            scheduling_status: "complete",
            blocker_count: 0,
            blocker_state: "none",
            has_children: false,
            child_count: 0,
            child_rollups: {
              total: 0,
              ready: 0,
              running: 0,
              paused_for_user: 0,
              blocked: 0,
              failed: 0,
              complete: 0,
              superseded: 0,
              not_compiled: 0,
            },
            created_at: "2026-03-11T00:00:00Z",
            last_updated_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
    },
    actionCatalogByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_version_id: "node-version-root",
        actions: [
          {
            action_id: "pause_run",
            label: "Pause Run",
            group: "execution",
            legal: true,
            blocked_reason: null,
            confirmation_mode: "inline",
            confirmation_label: "pause run",
            target_scope: "selected_node",
            details_json: {},
          },
        ],
      },
      "node-task-1": {
        node_id: "node-task-1",
        node_version_id: "node-version-task-1",
        actions: [
          { action_id: "start_run", label: "Start Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "start run", target_scope: "selected_node", details_json: {} },
          { action_id: "pause_run", label: "Pause Run", group: "execution", legal: false, blocked_reason: "node is not currently running", confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} },
          { action_id: "regenerate_node", label: "Regenerate Node", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "regenerate node", target_scope: "selected_node", details_json: {} },
        ],
      },
    },
    nodeSummaryByNodeId: {
      "node-root": {
        node_id: "node-root",
        parent_node_id: null,
        kind: "epic",
        tier: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow.",
        created_via: "manual",
        lifecycle_state: "READY",
        run_status: "RUNNING",
        current_run_id: "run-root",
        current_subtask_id: "subtask-root",
        current_subtask_attempt: 1,
        pause_flag_name: null,
        is_resumable: false,
        authoritative_node_version_id: "node-version-root",
        latest_created_node_version_id: "node-version-root",
        compiled_workflow_id: "workflow-root",
        active_branch_name: "node-root-v1",
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-task-1": {
        node_id: "node-task-1",
        parent_node_id: "node-root",
        kind: "task",
        tier: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell.",
        created_via: "manual",
        lifecycle_state: "COMPLETE",
        run_status: "COMPLETE",
        current_run_id: "run-task-1",
        current_subtask_id: null,
        current_subtask_attempt: null,
        pause_flag_name: null,
        is_resumable: false,
        authoritative_node_version_id: "node-version-task-1",
        latest_created_node_version_id: "node-version-task-1",
        compiled_workflow_id: "workflow-task-1",
        active_branch_name: "node-task-1-v1",
        seed_commit_sha: "def456",
        final_commit_sha: "fedcba",
      },
    },
    nodeLineageByNodeId: {
      "node-root": { logical_node_id: "node-root", authoritative_node_version_id: "node-version-root", latest_created_node_version_id: "node-version-root", versions: [{ id: "node-version-root" }] },
      "node-task-1": { logical_node_id: "node-task-1", authoritative_node_version_id: "node-version-task-1", latest_created_node_version_id: "node-version-task-1", versions: [{ id: "node-version-task-1" }] },
    },
    nodeVersionById: {
      "node-version-root": {
        id: "node-version-root",
        logical_node_id: "node-root",
        parent_node_version_id: null,
        tier: "epic",
        node_kind: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow.",
        description: null,
        status: "authoritative",
        version_number: 1,
        compiled_workflow_id: "workflow-root",
        supersedes_node_version_id: null,
        active_branch_name: "node-root-v1",
        branch_generation_number: 1,
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-version-task-1": {
        id: "node-version-task-1",
        logical_node_id: "node-task-1",
        parent_node_version_id: "node-version-root",
        tier: "task",
        node_kind: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell.",
        description: null,
        status: "authoritative",
        version_number: 1,
        compiled_workflow_id: "workflow-task-1",
        supersedes_node_version_id: null,
        active_branch_name: "node-task-1-v1",
        branch_generation_number: 1,
        seed_commit_sha: "def456",
        final_commit_sha: "fedcba",
      },
    },
    promptHistoryByNodeId: {
      "node-root": {
        node_id: "node-root",
        prompts: [
          {
            id: "prompt-root-1",
            node_version_id: "node-version-root",
            node_run_id: "run-root",
            compiled_subtask_id: "subtask-root",
            prompt_role: "execution",
            source_subtask_key: "research_context",
            template_path: "prompts/root.md",
            template_hash: "hash-root-prompt",
            content: "Investigate the website operator shell requirements.",
            content_hash: "hash-root-prompt-content",
            payload_json: {},
            delivered_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
      "node-task-1": {
        node_id: "node-task-1",
        prompts: [
          {
            id: "prompt-task-1",
            node_version_id: "node-version-task-1",
            node_run_id: "run-task-1",
            compiled_subtask_id: "subtask-task-1",
            prompt_role: "execution",
            source_subtask_key: "execute_node",
            template_path: "prompts/task.md",
            template_hash: "hash-task-prompt",
            content: "Build the first React shell for the operator website.",
            content_hash: "hash-task-prompt-content",
            payload_json: {},
            delivered_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
    },
    supersedeTemplateByNodeId: {
      "node-root": {
        id: "node-version-root-v2",
        logical_node_id: "node-root",
        parent_node_version_id: null,
        tier: "epic",
        node_kind: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow with stronger prompt review.",
        description: null,
        status: "candidate",
        version_number: 2,
        compiled_workflow_id: null,
        supersedes_node_version_id: "node-version-root",
        active_branch_name: "node-root-v2",
        branch_generation_number: 2,
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-task-1": {
        id: "node-version-task-1-v2",
        logical_node_id: "node-task-1",
        parent_node_version_id: "node-version-root",
        tier: "task",
        node_kind: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell with a real routed detail layout.",
        description: null,
        status: "candidate",
        version_number: 2,
        compiled_workflow_id: null,
        supersedes_node_version_id: "node-version-task-1",
        active_branch_name: "node-task-1-v2",
        branch_generation_number: 2,
        seed_commit_sha: "def456",
        final_commit_sha: null,
      },
    },
    regenerateResponseByNodeId: {
      "node-root": {
        root_node_id: "node-root",
        root_node_version_id: "node-version-root-v2",
        scope: "subtree",
        trigger_reason: "manual_regenerate",
        created_candidate_version_ids: ["node-version-root-v2"],
        stable_candidate_version_ids: ["node-version-root-v2"],
        rebuild_history: [],
      },
      "node-task-1": {
        root_node_id: "node-task-1",
        root_node_version_id: "node-version-task-1-v2",
        scope: "subtree",
        trigger_reason: "manual_regenerate",
        created_candidate_version_ids: ["node-version-task-1-v2"],
        stable_candidate_version_ids: ["node-version-task-1-v2"],
        rebuild_history: [],
      },
    },
    workflowByNodeId: {
      "node-root": {
        id: "workflow-root",
        node_version_id: "node-version-root",
        logical_node_id: "node-root",
        source_hash: "hash-root",
        built_in_library_version: "test",
        created_at: "2026-03-11T00:00:00Z",
        source_document_count: 4,
        task_count: 2,
        subtask_count: 3,
        compile_context: {},
        resolved_yaml: {},
        tasks: [
          { id: "task-a", task_key: "research_context", ordinal: 1, title: "Research", description: null, config_json: {}, subtasks: [{ id: "subtask-a1" }] },
          { id: "task-b", task_key: "execute_node", ordinal: 2, title: "Execute", description: null, config_json: {}, subtasks: [{ id: "subtask-b1" }, { id: "subtask-b2" }] },
        ],
      },
      "node-task-1": {
        id: "workflow-task-1",
        node_version_id: "node-version-task-1",
        logical_node_id: "node-task-1",
        source_hash: "hash-task-1",
        built_in_library_version: "test",
        created_at: "2026-03-11T00:00:00Z",
        source_document_count: 3,
        task_count: 1,
        subtask_count: 1,
        compile_context: {},
        resolved_yaml: {},
        tasks: [{ id: "task-x", task_key: "execute_node", ordinal: 1, title: "Execute", description: null, config_json: {}, subtasks: [{ id: "subtask-x1" }] }],
      },
    },
    runProgressByNodeId: {
      "node-root": { node_id: "node-root", run: { id: "run-root", trigger_reason: "workflow_start" }, current_subtask: { compiled_subtask_id: "subtask-root" }, current_attempt: { attempt_number: 1 } },
      "node-task-1": { node_id: "node-task-1", run: { id: "run-task-1", trigger_reason: "workflow_start" }, current_subtask: null, current_attempt: null },
    },
    runsByNodeId: {
      "node-root": { node_id: "node-root", runs: [{ id: "run-root", status: "RUNNING", trigger_reason: "workflow_start" }] },
      "node-task-1": { node_id: "node-task-1", runs: [{ id: "run-task-1", status: "COMPLETE", trigger_reason: "workflow_start" }] },
    },
    summariesByNodeId: {
      "node-root": { node_id: "node-root", summaries: [{ id: "summary-root", summary_type: "operator", summary_scope: "node", created_at: "2026-03-11T00:00:00Z" }] },
      "node-task-1": { node_id: "node-task-1", summaries: [{ id: "summary-task-1", summary_type: "operator", summary_scope: "node", created_at: "2026-03-11T00:00:00Z" }] },
    },
    sessionsByNodeId: {
      "node-root": { node_id: "node-root", sessions: [{ session_id: "session-root", status: "running", provider: "codex", session_role: "primary", backend: "tmux" }] },
      "node-task-1": { node_id: "node-task-1", sessions: [] },
    },
    sourcesByNodeId: {
      "node-root": { node_version_id: "node-version-root", logical_node_id: "node-root", source_documents: [{ id: "source-root", relative_path: "nodes/epic.yaml", source_role: "base_definition" }] },
      "node-task-1": { node_version_id: "node-version-task-1", logical_node_id: "node-task-1", source_documents: [{ id: "source-task-1", relative_path: "nodes/task.yaml", source_role: "base_definition" }] },
    },
    rationaleByNodeId: {
      "node-root": { node_id: "node-root", node_version_id: "node-version-root", prompt_record_id: null, summary_record_id: null, rationale_summary: "Root node establishes the website UI workstream.", change_counts: { added: 3, modified: 1 }, entity_history: [] },
      "node-task-1": { node_id: "node-task-1", node_version_id: "node-version-task-1", prompt_record_id: null, summary_record_id: null, rationale_summary: "Task node built the initial React shell.", change_counts: { added: 2, modified: 4 }, entity_history: [] },
    },
  },
};

SCENARIOS.empty_project_catalog = {
  id: "empty_project_catalog",
  projectCatalog: {
    daemon_context: {
      reachability_state: "reachable",
      auth_status: "valid",
      daemon_app_name: "AI Coding Daemon",
      daemon_version: "0.1.0",
      authority: "daemon",
      session_backend: "fake",
    },
    projects: [],
  },
  nodeKinds: {
    definitions: [],
    top_level_kinds: [],
  },
  projectBootstrapByProjectId: {},
  topLevelCreateResponseByProjectId: {},
  treeByNodeId: {},
  nodeSummaryByNodeId: {},
  nodeLineageByNodeId: {},
  nodeVersionById: {},
  promptHistoryByNodeId: {},
  supersedeTemplateByNodeId: {},
  regenerateResponseByNodeId: {},
  workflowByNodeId: {},
  runProgressByNodeId: {},
  runsByNodeId: {},
  summariesByNodeId: {},
  sessionsByNodeId: {},
  sourcesByNodeId: {},
  rationaleByNodeId: {},
  actionCatalogByNodeId: {},
};

SCENARIOS.top_level_create_failure = {
  ...structuredClone(SCENARIOS.project_catalog_single),
  id: "top_level_create_failure",
  topLevelCreateErrorByProjectId: {
    repo_alpha: {
      status: 400,
      detail: "mock top-level creation validation failure",
    },
  },
};

SCENARIOS.project_catalog_readiness_problem = {
  ...structuredClone(SCENARIOS.project_catalog_single),
  id: "project_catalog_readiness_problem",
};

SCENARIOS.project_catalog_readiness_problem.projectCatalog.projects = [
  {
    project_id: "repo_alpha",
    label: "repo_alpha",
    source_path: "repos/repo_alpha",
    bootstrap_ready: true,
    readiness_code: "ready",
    readiness_message: null,
    default_branch: "main",
    head_commit_sha: "abc1234def56",
  },
  {
    project_id: "repo_broken",
    label: "repo_broken",
    source_path: "repos/repo_broken",
    bootstrap_ready: false,
    readiness_code: "not_git_repo",
    readiness_message: "Directory is not a git repository.",
    default_branch: null,
    head_commit_sha: null,
  },
];
SCENARIOS.project_catalog_readiness_problem.projectBootstrapByProjectId = {
  repo_alpha: structuredClone(SCENARIOS.project_catalog_single.projectBootstrapByProjectId.repo_alpha),
  repo_broken: {
    project: {
      project_id: "repo_broken",
      label: "repo_broken",
      source_path: "repos/repo_broken",
      bootstrap_ready: false,
      readiness_code: "not_git_repo",
      readiness_message: "Directory is not a git repository.",
      default_branch: null,
      head_commit_sha: null,
    },
    root_node_id: null,
    route_hint: null,
  },
};

SCENARIOS.prompt_candidate_blocked = {
  ...structuredClone(SCENARIOS.healthy_tree_small),
  id: "prompt_candidate_blocked",
};

SCENARIOS.tree_filter_matrix = {
  ...structuredClone(SCENARIOS.healthy_tree_small),
  id: "tree_filter_matrix",
};

SCENARIOS.tree_filter_matrix.treeByNodeId["node-root"] = {
  root_node_id: "node-root",
  generated_at: "2026-03-11T00:00:00Z",
  nodes: [
    {
      node_id: "node-root",
      parent_node_id: null,
      depth: 0,
      kind: "epic",
      tier: "epic",
      title: "Website UI bootstrap",
      authoritative_node_version_id: "node-version-root",
      latest_created_node_version_id: "node-version-root",
      lifecycle_state: "READY",
      run_status: "RUNNING",
      scheduling_status: "already_running",
      blocker_count: 0,
      blocker_state: "none",
      has_children: true,
      child_count: 4,
      child_rollups: {
        total: 4,
        ready: 1,
        running: 0,
        paused_for_user: 1,
        blocked: 1,
        failed: 0,
        complete: 1,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-phase-1",
      parent_node_id: "node-root",
      depth: 1,
      kind: "phase",
      tier: "phase",
      title: "Phase waiting on children",
      authoritative_node_version_id: "node-version-phase-1",
      latest_created_node_version_id: "node-version-phase-1",
      lifecycle_state: "READY",
      run_status: null,
      scheduling_status: "blocked",
      blocker_count: 2,
      blocker_state: "blocked",
      has_children: true,
      child_count: 1,
      child_rollups: {
        total: 1,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 1,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-subtask-1",
      parent_node_id: "node-phase-1",
      depth: 2,
      kind: "task",
      tier: "task",
      title: "Inspect blocked child execution detail",
      authoritative_node_version_id: "node-version-subtask-1",
      latest_created_node_version_id: "node-version-subtask-1",
      lifecycle_state: "READY",
      run_status: null,
      scheduling_status: "blocked",
      blocker_count: 1,
      blocker_state: "blocked",
      has_children: false,
      child_count: 0,
      child_rollups: {
        total: 0,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 0,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-plan-1",
      parent_node_id: "node-root",
      depth: 1,
      kind: "plan",
      tier: "plan",
      title: "Plan waiting on user input",
      authoritative_node_version_id: "node-version-plan-1",
      latest_created_node_version_id: "node-version-plan-1",
      lifecycle_state: "PAUSED_FOR_USER",
      run_status: "PAUSED",
      scheduling_status: "paused_for_user",
      blocker_count: 0,
      blocker_state: "paused_for_user",
      has_children: false,
      child_count: 0,
      child_rollups: {
        total: 0,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 0,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-task-1",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Bootstrap React shell",
      authoritative_node_version_id: "node-version-task-1",
      latest_created_node_version_id: "node-version-task-1",
      lifecycle_state: "COMPLETE",
      run_status: "COMPLETE",
      scheduling_status: "complete",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: {
        total: 0,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 0,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-task-2",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Implement active sidebar filters",
      authoritative_node_version_id: "node-version-task-2",
      latest_created_node_version_id: "node-version-task-2",
      lifecycle_state: "RUNNING",
      run_status: "RUNNING",
      scheduling_status: "already_running",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: {
        total: 0,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 0,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
  ],
};

SCENARIOS.prompt_candidate_blocked.nodeLineageByNodeId["node-task-1"] = {
  logical_node_id: "node-task-1",
  authoritative_node_version_id: "node-version-task-1",
  latest_created_node_version_id: "node-version-task-1-v2",
  versions: [{ id: "node-version-task-1" }, { id: "node-version-task-1-v2" }],
};

SCENARIOS.prompt_candidate_blocked.nodeVersionById["node-version-task-1-v2"] = {
  id: "node-version-task-1-v2",
  logical_node_id: "node-task-1",
  parent_node_version_id: "node-version-root",
  tier: "task",
  node_kind: "task",
  title: "Bootstrap React shell",
  prompt: "Build the React shell with a real routed detail layout.",
  description: null,
  status: "candidate",
  version_number: 2,
  compiled_workflow_id: null,
  supersedes_node_version_id: "node-version-task-1",
  active_branch_name: "node-task-1-v2",
  branch_generation_number: 2,
  seed_commit_sha: "def456",
  final_commit_sha: null,
};

SCENARIOS.prompt_candidate_blocked.nodeSummaryByNodeId["node-task-1"] = {
  ...SCENARIOS.prompt_candidate_blocked.nodeSummaryByNodeId["node-task-1"],
  latest_created_node_version_id: "node-version-task-1-v2",
};

SCENARIOS.prompt_candidate_blocked.treeByNodeId["node-root"].nodes = SCENARIOS.prompt_candidate_blocked.treeByNodeId["node-root"].nodes.map((node) =>
  node.node_id === "node-task-1"
    ? {
        ...node,
        latest_created_node_version_id: "node-version-task-1-v2",
      }
    : node,
);

SCENARIOS.action_matrix = {
  ...structuredClone(SCENARIOS.project_catalog_single),
  id: "action_matrix",
};

SCENARIOS.action_matrix.treeByNodeId["node-root"] = {
  root_node_id: "node-root",
  generated_at: "2026-03-11T00:00:00Z",
  nodes: [
    {
      node_id: "node-root",
      parent_node_id: null,
      depth: 0,
      kind: "epic",
      tier: "epic",
      title: "Website UI bootstrap",
      authoritative_node_version_id: "node-version-root",
      latest_created_node_version_id: "node-version-root",
      lifecycle_state: "READY",
      run_status: "RUNNING",
      scheduling_status: "already_running",
      blocker_count: 0,
      blocker_state: "none",
      has_children: true,
      child_count: 9,
      child_rollups: {
        total: 9,
        ready: 7,
        running: 1,
        paused_for_user: 1,
        blocked: 0,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-pause",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Pause active run",
      authoritative_node_version_id: "node-version-pause",
      latest_created_node_version_id: "node-version-pause",
      lifecycle_state: "RUNNING",
      run_status: "RUNNING",
      scheduling_status: "already_running",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-resume",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Resume paused run",
      authoritative_node_version_id: "node-version-resume",
      latest_created_node_version_id: "node-version-resume",
      lifecycle_state: "PAUSED_FOR_USER",
      run_status: "PAUSED",
      scheduling_status: "paused_for_user",
      blocker_count: 0,
      blocker_state: "paused_for_user",
      has_children: false,
      child_count: 0,
      child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-attach",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Attach session",
      authoritative_node_version_id: "node-version-attach",
      latest_created_node_version_id: "node-version-attach",
      lifecycle_state: "RUNNING",
      run_status: "RUNNING",
      scheduling_status: "already_running",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-session-resume",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Resume session",
      authoritative_node_version_id: "node-version-session-resume",
      latest_created_node_version_id: "node-version-session-resume",
      lifecycle_state: "PAUSED_FOR_USER",
      run_status: "PAUSED",
      scheduling_status: "paused_for_user",
      blocker_count: 0,
      blocker_state: "paused_for_user",
      has_children: false,
      child_count: 0,
      child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-provider-resume",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Provider resume",
      authoritative_node_version_id: "node-version-provider-resume",
      latest_created_node_version_id: "node-version-provider-resume",
      lifecycle_state: "PAUSED_FOR_USER",
      run_status: "PAUSED",
      scheduling_status: "paused_for_user",
      blocker_count: 0,
      blocker_state: "paused_for_user",
      has_children: false,
      child_count: 0,
      child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-reconcile",
      parent_node_id: "node-root",
      depth: 1,
      kind: "phase",
      tier: "phase",
      title: "Reconcile children",
      authoritative_node_version_id: "node-version-reconcile",
      latest_created_node_version_id: "node-version-reconcile",
      lifecycle_state: "READY",
      run_status: null,
      scheduling_status: "ready",
      blocker_count: 0,
      blocker_state: "none",
      has_children: true,
      child_count: 1,
      child_rollups: { total: 1, ready: 1, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-regenerate",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Regenerate subtree",
      authoritative_node_version_id: "node-version-regenerate",
      latest_created_node_version_id: "node-version-regenerate",
      lifecycle_state: "READY",
      run_status: null,
      scheduling_status: "ready",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-empty-actions",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Empty actions",
      authoritative_node_version_id: "node-version-empty-actions",
      latest_created_node_version_id: "node-version-empty-actions",
      lifecycle_state: "COMPLETE",
      run_status: "COMPLETE",
      scheduling_status: "complete",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-empty-prompts",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Empty prompts",
      authoritative_node_version_id: "node-version-empty-prompts",
      latest_created_node_version_id: "node-version-empty-prompts",
      lifecycle_state: "READY",
      run_status: null,
      scheduling_status: "ready",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
  ],
};

SCENARIOS.action_matrix.actionCatalogByNodeId = {
  "node-pause": {
    node_id: "node-pause",
    node_version_id: "node-version-pause",
    actions: [{ action_id: "pause_run", label: "Pause Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} }],
  },
  "node-resume": {
    node_id: "node-resume",
    node_version_id: "node-version-resume",
    actions: [{ action_id: "resume_run", label: "Resume Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "resume run", target_scope: "selected_node", details_json: {} }],
  },
  "node-attach": {
    node_id: "node-attach",
    node_version_id: "node-version-attach",
    actions: [{ action_id: "session_attach", label: "Attach Session", group: "session", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "attach session", target_scope: "selected_node", details_json: {} }],
  },
  "node-session-resume": {
    node_id: "node-session-resume",
    node_version_id: "node-version-session-resume",
    actions: [{ action_id: "session_resume", label: "Resume Session", group: "session", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "resume session", target_scope: "selected_node", details_json: {} }],
  },
  "node-provider-resume": {
    node_id: "node-provider-resume",
    node_version_id: "node-version-provider-resume",
    actions: [{ action_id: "session_provider_resume", label: "Provider Resume", group: "session", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "resume provider session", target_scope: "selected_node", details_json: {} }],
  },
  "node-reconcile": {
    node_id: "node-reconcile",
    node_version_id: "node-version-reconcile",
    actions: [{ action_id: "reconcile_children:accept_generated", label: "Reconcile Children", group: "structure", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "accept generated", target_scope: "selected_node", details_json: { decision: "accept_generated" } }],
  },
  "node-regenerate": {
    node_id: "node-regenerate",
    node_version_id: "node-version-regenerate",
    actions: [{ action_id: "regenerate_node", label: "Regenerate Node", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "regenerate node", target_scope: "selected_node", details_json: {} }],
  },
  "node-empty-actions": {
    node_id: "node-empty-actions",
    node_version_id: "node-version-empty-actions",
    actions: [],
  },
};

SCENARIOS.action_matrix.regenerateResponseByNodeId["node-regenerate"] = {
  root_node_version_id: "node-version-regenerate-v2",
  created_candidate_version_ids: ["node-version-regenerate-v2"],
  stable_candidate_version_ids: ["node-version-regenerate-v2"],
  root_logical_node_id: "node-regenerate",
  scope: "subtree",
  status: "ready_for_cutover",
};

SCENARIOS.action_matrix.nodeSummaryByNodeId["node-empty-prompts"] = {
  node_id: "node-empty-prompts",
  parent_node_id: "node-root",
  kind: "task",
  tier: "task",
  title: "Empty prompts",
  prompt: "This node has not delivered prompts yet.",
  created_via: "manual",
  lifecycle_state: "READY",
  run_status: null,
  current_run_id: null,
  current_subtask_id: null,
  current_subtask_attempt: null,
  pause_flag_name: null,
  is_resumable: false,
  authoritative_node_version_id: "node-version-empty-prompts",
  latest_created_node_version_id: "node-version-empty-prompts",
  compiled_workflow_id: "workflow-empty-prompts",
  active_branch_name: "node-empty-prompts-v1",
  seed_commit_sha: "empty111",
  final_commit_sha: null,
};
SCENARIOS.action_matrix.nodeLineageByNodeId["node-empty-prompts"] = {
  logical_node_id: "node-empty-prompts",
  authoritative_node_version_id: "node-version-empty-prompts",
  latest_created_node_version_id: "node-version-empty-prompts",
  versions: [{ id: "node-version-empty-prompts" }],
};
SCENARIOS.action_matrix.nodeVersionById["node-version-empty-prompts"] = {
  id: "node-version-empty-prompts",
  logical_node_id: "node-empty-prompts",
  parent_node_version_id: "node-version-root",
  tier: "task",
  node_kind: "task",
  title: "Empty prompts",
  prompt: "This node has not delivered prompts yet.",
  description: null,
  status: "authoritative",
  version_number: 1,
  compiled_workflow_id: "workflow-empty-prompts",
  supersedes_node_version_id: null,
  active_branch_name: "node-empty-prompts-v1",
  branch_generation_number: 1,
  seed_commit_sha: "empty111",
  final_commit_sha: null,
};
SCENARIOS.action_matrix.promptHistoryByNodeId["node-empty-prompts"] = {
  node_id: "node-empty-prompts",
  prompts: [],
};

SCENARIOS.shared_state_matrix = {
  ...structuredClone(SCENARIOS.action_matrix),
  id: "shared_state_matrix",
  routeDelayMs: {
    "GET /api/projects": 1200,
    "GET /api/projects/repo_alpha/bootstrap": 1200,
    "GET /api/nodes/node-root/tree": 1200,
    "GET /api/nodes/node-loading-actions/actions": 1200,
  },
  routeOverrides: {
    "GET /api/nodes/node-empty-prompts/prompt-history": {
      status: 200,
      delay_ms: 1200,
      payload: {
        node_id: "node-empty-prompts",
        prompts: [],
      },
    },
    "GET /api/nodes/node-error-actions/actions": {
      status: 500,
      payload: { detail: "mock action catalog failure" },
    },
    "GET /api/nodes/node-error-prompts/prompt-history": {
      status: 500,
      payload: { detail: "mock prompt history failure" },
    },
  },
};

SCENARIOS.shared_state_matrix.treeByNodeId["node-root"].nodes = [
  ...SCENARIOS.shared_state_matrix.treeByNodeId["node-root"].nodes,
  {
    node_id: "node-loading-actions",
    parent_node_id: "node-root",
    depth: 1,
    kind: "task",
    tier: "task",
    title: "Loading actions",
    authoritative_node_version_id: "node-version-loading-actions",
    latest_created_node_version_id: "node-version-loading-actions",
    lifecycle_state: "READY",
    run_status: null,
    scheduling_status: "ready",
    blocker_count: 0,
    blocker_state: "none",
    has_children: false,
    child_count: 0,
    child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
    created_at: "2026-03-11T00:00:00Z",
    last_updated_at: "2026-03-11T00:00:00Z",
  },
  {
    node_id: "node-error-actions",
    parent_node_id: "node-root",
    depth: 1,
    kind: "task",
    tier: "task",
    title: "Error actions",
    authoritative_node_version_id: "node-version-error-actions",
    latest_created_node_version_id: "node-version-error-actions",
    lifecycle_state: "READY",
    run_status: null,
    scheduling_status: "ready",
    blocker_count: 0,
    blocker_state: "none",
    has_children: false,
    child_count: 0,
    child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
    created_at: "2026-03-11T00:00:00Z",
    last_updated_at: "2026-03-11T00:00:00Z",
  },
  {
    node_id: "node-error-prompts",
    parent_node_id: "node-root",
    depth: 1,
    kind: "task",
    tier: "task",
    title: "Error prompts",
    authoritative_node_version_id: "node-version-error-prompts",
    latest_created_node_version_id: "node-version-error-prompts",
    lifecycle_state: "READY",
    run_status: null,
    scheduling_status: "ready",
    blocker_count: 0,
    blocker_state: "none",
    has_children: false,
    child_count: 0,
    child_rollups: { total: 0, ready: 0, running: 0, paused_for_user: 0, blocked: 0, failed: 0, complete: 0, superseded: 0, not_compiled: 0 },
    created_at: "2026-03-11T00:00:00Z",
    last_updated_at: "2026-03-11T00:00:00Z",
  },
];
SCENARIOS.shared_state_matrix.treeByNodeId["node-root"].nodes[0] = {
  ...SCENARIOS.shared_state_matrix.treeByNodeId["node-root"].nodes[0],
  child_count: 12,
  child_rollups: {
    total: 12,
    ready: 10,
    running: 1,
    paused_for_user: 1,
    blocked: 0,
    failed: 0,
    complete: 0,
    superseded: 0,
    not_compiled: 0,
  },
};

SCENARIOS.shared_state_matrix.actionCatalogByNodeId["node-loading-actions"] = {
  node_id: "node-loading-actions",
  node_version_id: "node-version-loading-actions",
  actions: [{ action_id: "pause_run", label: "Pause Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} }],
};
SCENARIOS.shared_state_matrix.actionCatalogByNodeId["node-error-actions"] = {
  node_id: "node-error-actions",
  node_version_id: "node-version-error-actions",
  actions: [{ action_id: "pause_run", label: "Pause Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} }],
};
SCENARIOS.shared_state_matrix.nodeSummaryByNodeId["node-error-prompts"] = {
  ...SCENARIOS.shared_state_matrix.nodeSummaryByNodeId["node-empty-prompts"],
  node_id: "node-error-prompts",
  title: "Error prompts",
  authoritative_node_version_id: "node-version-error-prompts",
  latest_created_node_version_id: "node-version-error-prompts",
  compiled_workflow_id: "workflow-error-prompts",
  active_branch_name: "node-error-prompts-v1",
  seed_commit_sha: "error111",
};
SCENARIOS.shared_state_matrix.nodeLineageByNodeId["node-error-prompts"] = {
  logical_node_id: "node-error-prompts",
  authoritative_node_version_id: "node-version-error-prompts",
  latest_created_node_version_id: "node-version-error-prompts",
  versions: [{ id: "node-version-error-prompts" }],
};
SCENARIOS.shared_state_matrix.nodeVersionById["node-version-error-prompts"] = {
  ...SCENARIOS.shared_state_matrix.nodeVersionById["node-version-empty-prompts"],
  id: "node-version-error-prompts",
  logical_node_id: "node-error-prompts",
  title: "Error prompts",
  compiled_workflow_id: "workflow-error-prompts",
  active_branch_name: "node-error-prompts-v1",
  seed_commit_sha: "error111",
};
SCENARIOS.shared_state_matrix.promptHistoryByNodeId["node-error-prompts"] = {
  node_id: "node-error-prompts",
  prompts: [],
};

SCENARIOS.tree_error_matrix = {
  ...structuredClone(SCENARIOS.action_matrix),
  id: "tree_error_matrix",
  routeOverrides: {
    "GET /api/nodes/node-root/tree": {
      status: 500,
      payload: { detail: "mock tree load failure" },
    },
  },
};

function ensureProjectBootstrapRootCatalogs() {
  for (const scenario of Object.values(SCENARIOS)) {
    for (const [projectId, bootstrap] of Object.entries(scenario.projectBootstrapByProjectId ?? {})) {
      if (bootstrap.top_level_nodes) {
        continue;
      }
      if (!bootstrap.root_node_id) {
        bootstrap.top_level_nodes = [];
        continue;
      }
      const routeHint =
        bootstrap.route_hint ??
        {
          project_id: projectId,
          node_id: bootstrap.root_node_id,
          tab: "overview",
          url: `/projects/${projectId}/nodes/${bootstrap.root_node_id}/overview`,
        };
      const tree = scenario.treeByNodeId?.[bootstrap.root_node_id];
      const rootNode = tree?.nodes?.find((entry) => entry.node_id === bootstrap.root_node_id);
      bootstrap.top_level_nodes = [
        {
          node_id: bootstrap.root_node_id,
          kind: rootNode?.kind ?? "epic",
          tier: rootNode?.tier ?? "epic",
          title: rootNode?.title ?? bootstrap.root_node_id,
          lifecycle_state: rootNode?.lifecycle_state ?? null,
          run_status: rootNode?.run_status ?? null,
          authoritative_node_version_id: rootNode?.authoritative_node_version_id ?? null,
          latest_created_node_version_id: rootNode?.latest_created_node_version_id ?? null,
          route_hint: routeHint,
        },
      ];
    }
  }
}

ensureProjectBootstrapRootCatalogs();
