export const SCENARIOS = {
  project_catalog_single: {
    id: "project_catalog_single",
    projectCatalog: {
      daemon_context: {
        reachability_state: "reachable",
        auth_status: "valid",
        daemon_app_name: "AI Coding Daemon",
        daemon_version: "0.1.0",
        authority: "daemon",
        session_backend: "fake",
      },
      projects: [
        {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
          bootstrap_ready: true,
          readiness_code: "ready",
          readiness_message: null,
          default_branch: "main",
          head_commit_sha: "abc1234def56",
        },
      ],
    },
    nodeKinds: {
      definitions: [
        {
          kind: "epic",
          tier: "epic",
          description: "Epic node",
          allow_parentless: true,
          allowed_parent_kinds: [],
          allowed_child_kinds: ["phase"],
        },
      ],
      top_level_kinds: ["epic"],
    },
    topLevelCreateResponseByProjectId: {
      repo_alpha: {
        status: "started",
        requested_start_run: true,
        resolved_title: "Website UI bootstrap",
        project: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        source_repo: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        bootstrap: {
          repo_bootstrap_status: "bootstrapped",
          worker_repo_path: "/mock-runtime/git/node_versions/node-version-root",
          branch_name: "tier/epic/epic/website-ui-bootstrap__node-root/v1",
          seed_commit_sha: "abc1234",
          head_commit_sha: "abc1234",
          working_tree_state: "seed_ready",
        },
        node: {
          node_id: "node-root",
          parent_node_id: null,
          kind: "epic",
          tier: "epic",
          title: "Website UI bootstrap",
          prompt: "Create the initial website UI workflow.",
          created_via: "manual",
        },
        node_version_id: "node-version-root",
        compile: {
          status: "compiled",
          node_version_id: "node-version-root",
          logical_node_id: "node-root",
          compile_context: {},
        },
        lifecycle: {
          node_id: "node-root",
          lifecycle_state: "RUNNING",
          run_status: "RUNNING",
          current_run_id: "run-root",
          current_task_id: null,
          current_subtask_id: null,
          current_subtask_attempt: null,
          last_completed_subtask_id: null,
          execution_cursor_json: {},
          failure_count_from_children: 0,
          failure_count_consecutive: 0,
          defer_to_user_threshold: 0,
          is_resumable: false,
          pause_flag_name: null,
          working_tree_state: null,
          updated_at: "2026-03-11T00:00:00Z",
        },
        run_admission: {
          status: "admitted",
          node_id: "node-root",
          node_run_id: "run-root",
          trigger_reason: "workflow_start",
        },
        run_progress: {
          node_id: "node-root",
          run: {
            id: "run-root",
            logical_node_id: "node-root",
            trigger_reason: "workflow_start",
          },
          current_subtask: null,
          current_attempt: null,
        },
        route_hint: {
          project_id: "repo_alpha",
          node_id: "node-root",
          tab: "overview",
          url: "/projects/repo_alpha/nodes/node-root/overview",
        },
      },
    },
    projectBootstrapByProjectId: {
      repo_alpha: {
        project: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        root_node_id: null,
        route_hint: null,
      },
    },
    treeByNodeId: {
      "node-root": {
        root_node_id: "node-root",
        generated_at: "2026-03-11T00:00:00Z",
        nodes: [
          {
            node_id: "node-root",
            parent_node_id: null,
            depth: 0,
            kind: "epic",
            tier: "epic",
            title: "Website UI bootstrap",
            authoritative_node_version_id: "node-version-root",
            latest_created_node_version_id: "node-version-root",
            lifecycle_state: "READY",
            run_status: "RUNNING",
            scheduling_status: "already_running",
            blocker_count: 0,
            blocker_state: "none",
            has_children: true,
            child_count: 1,
            child_rollups: {
              total: 1,
              ready: 0,
              running: 0,
              paused_for_user: 0,
              blocked: 0,
              failed: 0,
              complete: 1,
              superseded: 0,
              not_compiled: 0,
            },
            created_at: "2026-03-11T00:00:00Z",
            last_updated_at: "2026-03-11T00:00:00Z",
          },
          {
            node_id: "node-task-1",
            parent_node_id: "node-root",
            depth: 1,
            kind: "task",
            tier: "task",
            title: "Bootstrap React shell",
            authoritative_node_version_id: "node-version-task-1",
            latest_created_node_version_id: "node-version-task-1",
            lifecycle_state: "COMPLETE",
            run_status: "COMPLETE",
            scheduling_status: "complete",
            blocker_count: 0,
            blocker_state: "none",
            has_children: false,
            child_count: 0,
            child_rollups: {
              total: 0,
              ready: 0,
              running: 0,
              paused_for_user: 0,
              blocked: 0,
              failed: 0,
              complete: 0,
              superseded: 0,
              not_compiled: 0,
            },
            created_at: "2026-03-11T00:00:00Z",
            last_updated_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
    },
    nodeSummaryByNodeId: {
      "node-root": {
        node_id: "node-root",
        parent_node_id: null,
        kind: "epic",
        tier: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow.",
        created_via: "manual",
        lifecycle_state: "READY",
        run_status: "RUNNING",
        current_run_id: "run-root",
        current_subtask_id: "subtask-root",
        current_subtask_attempt: 1,
        pause_flag_name: null,
        is_resumable: false,
        authoritative_node_version_id: "node-version-root",
        latest_created_node_version_id: "node-version-root",
        compiled_workflow_id: "workflow-root",
        active_branch_name: "node-root-v1",
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-task-1": {
        node_id: "node-task-1",
        parent_node_id: "node-root",
        kind: "task",
        tier: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell.",
        created_via: "manual",
        lifecycle_state: "COMPLETE",
        run_status: "COMPLETE",
        current_run_id: "run-task-1",
        current_subtask_id: null,
        current_subtask_attempt: null,
        pause_flag_name: null,
        is_resumable: false,
        authoritative_node_version_id: "node-version-task-1",
        latest_created_node_version_id: "node-version-task-1",
        compiled_workflow_id: "workflow-task-1",
        active_branch_name: "node-task-1-v1",
        seed_commit_sha: "def456",
        final_commit_sha: "fedcba",
      },
    },
    nodeLineageByNodeId: {
      "node-root": {
        logical_node_id: "node-root",
        authoritative_node_version_id: "node-version-root",
        latest_created_node_version_id: "node-version-root",
        versions: [{ id: "node-version-root" }],
      },
      "node-task-1": {
        logical_node_id: "node-task-1",
        authoritative_node_version_id: "node-version-task-1",
        latest_created_node_version_id: "node-version-task-1",
        versions: [{ id: "node-version-task-1" }],
      },
    },
    nodeVersionById: {
      "node-version-root": {
        id: "node-version-root",
        logical_node_id: "node-root",
        parent_node_version_id: null,
        tier: "epic",
        node_kind: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow.",
        description: null,
        status: "authoritative",
        version_number: 1,
        compiled_workflow_id: "workflow-root",
        supersedes_node_version_id: null,
        active_branch_name: "node-root-v1",
        branch_generation_number: 1,
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-version-task-1": {
        id: "node-version-task-1",
        logical_node_id: "node-task-1",
        parent_node_version_id: "node-version-root",
        tier: "task",
        node_kind: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell.",
        description: null,
        status: "authoritative",
        version_number: 1,
        compiled_workflow_id: "workflow-task-1",
        supersedes_node_version_id: null,
        active_branch_name: "node-task-1-v1",
        branch_generation_number: 1,
        seed_commit_sha: "def456",
        final_commit_sha: "fedcba",
      },
    },
    promptHistoryByNodeId: {
      "node-root": {
        node_id: "node-root",
        prompts: [
          {
            id: "prompt-root-1",
            node_version_id: "node-version-root",
            node_run_id: "run-root",
            compiled_subtask_id: "subtask-root",
            prompt_role: "execution",
            source_subtask_key: "research_context",
            template_path: "prompts/root.md",
            template_hash: "hash-root-prompt",
            content: "Investigate the website operator shell requirements.",
            content_hash: "hash-root-prompt-content",
            payload_json: {},
            delivered_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
      "node-task-1": {
        node_id: "node-task-1",
        prompts: [
          {
            id: "prompt-task-1",
            node_version_id: "node-version-task-1",
            node_run_id: "run-task-1",
            compiled_subtask_id: "subtask-task-1",
            prompt_role: "execution",
            source_subtask_key: "execute_node",
            template_path: "prompts/task.md",
            template_hash: "hash-task-prompt",
            content: "Build the first React shell for the operator website.",
            content_hash: "hash-task-prompt-content",
            payload_json: {},
            delivered_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
    },
    supersedeTemplateByNodeId: {
      "node-root": {
        id: "node-version-root-v2",
        logical_node_id: "node-root",
        parent_node_version_id: null,
        tier: "epic",
        node_kind: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow with stronger prompt review.",
        description: null,
        status: "candidate",
        version_number: 2,
        compiled_workflow_id: null,
        supersedes_node_version_id: "node-version-root",
        active_branch_name: "node-root-v2",
        branch_generation_number: 2,
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-task-1": {
        id: "node-version-task-1-v2",
        logical_node_id: "node-task-1",
        parent_node_version_id: "node-version-root",
        tier: "task",
        node_kind: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell with a real routed detail layout.",
        description: null,
        status: "candidate",
        version_number: 2,
        compiled_workflow_id: null,
        supersedes_node_version_id: "node-version-task-1",
        active_branch_name: "node-task-1-v2",
        branch_generation_number: 2,
        seed_commit_sha: "def456",
        final_commit_sha: null,
      },
    },
    regenerateResponseByNodeId: {
      "node-root": {
        root_node_id: "node-root",
        root_node_version_id: "node-version-root-v2",
        scope: "subtree",
        trigger_reason: "manual_regenerate",
        created_candidate_version_ids: ["node-version-root-v2"],
        stable_candidate_version_ids: ["node-version-root-v2"],
        rebuild_history: [],
      },
      "node-task-1": {
        root_node_id: "node-task-1",
        root_node_version_id: "node-version-task-1-v2",
        scope: "subtree",
        trigger_reason: "manual_regenerate",
        created_candidate_version_ids: ["node-version-task-1-v2"],
        stable_candidate_version_ids: ["node-version-task-1-v2"],
        rebuild_history: [],
      },
    },
    workflowByNodeId: {
      "node-root": {
        id: "workflow-root",
        node_version_id: "node-version-root",
        logical_node_id: "node-root",
        source_hash: "hash-root",
        built_in_library_version: "test",
        created_at: "2026-03-11T00:00:00Z",
        source_document_count: 4,
        task_count: 2,
        subtask_count: 3,
        compile_context: {},
        resolved_yaml: {},
        tasks: [
          { id: "task-a", task_key: "research_context", ordinal: 1, title: "Research", description: null, config_json: {}, subtasks: [{ id: "subtask-a1" }] },
          { id: "task-b", task_key: "execute_node", ordinal: 2, title: "Execute", description: null, config_json: {}, subtasks: [{ id: "subtask-b1" }, { id: "subtask-b2" }] },
        ],
      },
      "node-task-1": {
        id: "workflow-task-1",
        node_version_id: "node-version-task-1",
        logical_node_id: "node-task-1",
        source_hash: "hash-task-1",
        built_in_library_version: "test",
        created_at: "2026-03-11T00:00:00Z",
        source_document_count: 3,
        task_count: 1,
        subtask_count: 1,
        compile_context: {},
        resolved_yaml: {},
        tasks: [{ id: "task-x", task_key: "execute_node", ordinal: 1, title: "Execute", description: null, config_json: {}, subtasks: [{ id: "subtask-x1" }] }],
      },
    },
    runProgressByNodeId: {
      "node-root": {
        node_id: "node-root",
        run: { id: "run-root", trigger_reason: "workflow_start" },
        current_subtask: { compiled_subtask_id: "subtask-root" },
        current_attempt: { attempt_number: 1 },
      },
      "node-task-1": {
        node_id: "node-task-1",
        run: { id: "run-task-1", trigger_reason: "workflow_start" },
        current_subtask: null,
        current_attempt: null,
      },
    },
    runsByNodeId: {
      "node-root": {
        node_id: "node-root",
        runs: [{ id: "run-root", status: "RUNNING", trigger_reason: "workflow_start" }],
      },
      "node-task-1": {
        node_id: "node-task-1",
        runs: [{ id: "run-task-1", status: "COMPLETE", trigger_reason: "workflow_start" }],
      },
    },
    summariesByNodeId: {
      "node-root": {
        node_id: "node-root",
        summaries: [{ id: "summary-root", summary_type: "operator", summary_scope: "node", created_at: "2026-03-11T00:00:00Z" }],
      },
      "node-task-1": {
        node_id: "node-task-1",
        summaries: [{ id: "summary-task-1", summary_type: "operator", summary_scope: "node", created_at: "2026-03-11T00:00:00Z" }],
      },
    },
    sessionsByNodeId: {
      "node-root": {
        node_id: "node-root",
        sessions: [{ session_id: "session-root", status: "running", provider: "codex", session_role: "primary", backend: "tmux" }],
      },
      "node-task-1": {
        node_id: "node-task-1",
        sessions: [],
      },
    },
    sourcesByNodeId: {
      "node-root": {
        node_version_id: "node-version-root",
        logical_node_id: "node-root",
        source_documents: [{ id: "source-root", relative_path: "nodes/epic.yaml", source_role: "base_definition" }],
      },
      "node-task-1": {
        node_version_id: "node-version-task-1",
        logical_node_id: "node-task-1",
        source_documents: [{ id: "source-task-1", relative_path: "nodes/task.yaml", source_role: "base_definition" }],
      },
    },
    rationaleByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_version_id: "node-version-root",
        prompt_record_id: null,
        summary_record_id: null,
        rationale_summary: "Root node establishes the website UI workstream.",
        change_counts: { added: 3, modified: 1 },
        entity_history: [],
      },
      "node-task-1": {
        node_id: "node-task-1",
        node_version_id: "node-version-task-1",
        prompt_record_id: null,
        summary_record_id: null,
        rationale_summary: "Task node built the initial React shell.",
        change_counts: { added: 2, modified: 4 },
        entity_history: [],
      },
    },
    actionCatalogByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_version_id: "node-version-root",
        actions: [
          { action_id: "pause_run", label: "Pause Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} },
          { action_id: "regenerate_node", label: "Regenerate Node", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "regenerate node", target_scope: "selected_node", details_json: {} },
        ],
      },
      "node-task-1": {
        node_id: "node-task-1",
        node_version_id: "node-version-task-1",
        actions: [
          { action_id: "start_run", label: "Start Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "start run", target_scope: "selected_node", details_json: {} },
          { action_id: "pause_run", label: "Pause Run", group: "execution", legal: false, blocked_reason: "node is not currently running", confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} },
          { action_id: "regenerate_node", label: "Regenerate Node", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "regenerate node", target_scope: "selected_node", details_json: {} },
        ],
      },
    },
  },
  healthy_tree_small: {
    id: "healthy_tree_small",
    projectCatalog: {
      daemon_context: {
        reachability_state: "reachable",
        auth_status: "valid",
        daemon_app_name: "AI Coding Daemon",
        daemon_version: "0.1.0",
        authority: "daemon",
        session_backend: "fake",
      },
      projects: [
        {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
          bootstrap_ready: true,
          readiness_code: "ready",
          readiness_message: null,
          default_branch: "main",
          head_commit_sha: "abc1234def56",
        },
      ],
    },
    nodeKinds: {
      definitions: [
        {
          kind: "epic",
          tier: "epic",
          description: "Epic node",
          allow_parentless: true,
          allowed_parent_kinds: [],
          allowed_child_kinds: ["phase"],
        },
        {
          kind: "task",
          tier: "task",
          description: "Task node",
          allow_parentless: true,
          allowed_parent_kinds: [],
          allowed_child_kinds: [],
        },
      ],
      top_level_kinds: ["epic", "task"],
    },
    topLevelCreateResponseByProjectId: {
      repo_alpha: {
        status: "started",
        requested_start_run: true,
        resolved_title: "Website UI bootstrap",
        project: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        source_repo: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        bootstrap: {
          repo_bootstrap_status: "bootstrapped",
          worker_repo_path: "/mock-runtime/git/node_versions/node-version-root",
          branch_name: "tier/epic/epic/website-ui-bootstrap__node-root/v1",
          seed_commit_sha: "abc1234",
          head_commit_sha: "abc1234",
          working_tree_state: "seed_ready",
        },
        node: {
          node_id: "node-root",
          parent_node_id: null,
          kind: "epic",
          tier: "epic",
          title: "Website UI bootstrap",
          prompt: "Create the initial website UI workflow.",
          created_via: "manual",
        },
        node_version_id: "node-version-root",
        compile: {
          status: "compiled",
          node_version_id: "node-version-root",
          logical_node_id: "node-root",
          compile_context: {},
        },
        lifecycle: {
          node_id: "node-root",
          lifecycle_state: "RUNNING",
          run_status: "RUNNING",
          current_run_id: "run-root",
          current_task_id: null,
          current_subtask_id: null,
          current_subtask_attempt: null,
          last_completed_subtask_id: null,
          execution_cursor_json: {},
          failure_count_from_children: 0,
          failure_count_consecutive: 0,
          defer_to_user_threshold: 0,
          is_resumable: false,
          pause_flag_name: null,
          working_tree_state: null,
          updated_at: "2026-03-11T00:00:00Z",
        },
        run_admission: {
          status: "admitted",
          node_id: "node-root",
          node_run_id: "run-root",
          trigger_reason: "workflow_start",
        },
        run_progress: {
          node_id: "node-root",
          run: {
            id: "run-root",
            logical_node_id: "node-root",
            trigger_reason: "workflow_start",
          },
          current_subtask: null,
          current_attempt: null,
        },
        route_hint: {
          project_id: "repo_alpha",
          node_id: "node-root",
          tab: "overview",
          url: "/projects/repo_alpha/nodes/node-root/overview",
        },
      },
    },
    projectBootstrapByProjectId: {
      repo_alpha: {
        project: {
          project_id: "repo_alpha",
          label: "repo_alpha",
          source_path: "repos/repo_alpha",
        },
        root_node_id: "node-root",
        route_hint: {
          project_id: "repo_alpha",
          node_id: "node-root",
          tab: "overview",
          url: "/projects/repo_alpha/nodes/node-root/overview",
        },
      },
    },
    treeByNodeId: {
      "node-root": {
        root_node_id: "node-root",
        generated_at: "2026-03-11T00:00:00Z",
        nodes: [
          {
            node_id: "node-root",
            parent_node_id: null,
            depth: 0,
            kind: "epic",
            tier: "epic",
            title: "Website UI bootstrap",
            authoritative_node_version_id: "node-version-root",
            latest_created_node_version_id: "node-version-root",
            lifecycle_state: "READY",
            run_status: "RUNNING",
            scheduling_status: "already_running",
            blocker_count: 0,
            blocker_state: "none",
            has_children: true,
            child_count: 1,
            child_rollups: {
              total: 1,
              ready: 0,
              running: 0,
              paused_for_user: 0,
              blocked: 0,
              failed: 0,
              complete: 1,
              superseded: 0,
              not_compiled: 0,
            },
            created_at: "2026-03-11T00:00:00Z",
            last_updated_at: "2026-03-11T00:00:00Z",
          },
          {
            node_id: "node-task-1",
            parent_node_id: "node-root",
            depth: 1,
            kind: "task",
            tier: "task",
            title: "Bootstrap React shell",
            authoritative_node_version_id: "node-version-task-1",
            latest_created_node_version_id: "node-version-task-1",
            lifecycle_state: "COMPLETE",
            run_status: "COMPLETE",
            scheduling_status: "complete",
            blocker_count: 0,
            blocker_state: "none",
            has_children: false,
            child_count: 0,
            child_rollups: {
              total: 0,
              ready: 0,
              running: 0,
              paused_for_user: 0,
              blocked: 0,
              failed: 0,
              complete: 0,
              superseded: 0,
              not_compiled: 0,
            },
            created_at: "2026-03-11T00:00:00Z",
            last_updated_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
    },
    actionCatalogByNodeId: {
      "node-root": {
        node_id: "node-root",
        node_version_id: "node-version-root",
        actions: [
          {
            action_id: "pause_run",
            label: "Pause Run",
            group: "execution",
            legal: true,
            blocked_reason: null,
            confirmation_mode: "inline",
            confirmation_label: "pause run",
            target_scope: "selected_node",
            details_json: {},
          },
        ],
      },
      "node-task-1": {
        node_id: "node-task-1",
        node_version_id: "node-version-task-1",
        actions: [
          { action_id: "start_run", label: "Start Run", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "start run", target_scope: "selected_node", details_json: {} },
          { action_id: "pause_run", label: "Pause Run", group: "execution", legal: false, blocked_reason: "node is not currently running", confirmation_mode: "inline", confirmation_label: "pause run", target_scope: "selected_node", details_json: {} },
          { action_id: "regenerate_node", label: "Regenerate Node", group: "execution", legal: true, blocked_reason: null, confirmation_mode: "inline", confirmation_label: "regenerate node", target_scope: "selected_node", details_json: {} },
        ],
      },
    },
    nodeSummaryByNodeId: {
      "node-root": {
        node_id: "node-root",
        parent_node_id: null,
        kind: "epic",
        tier: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow.",
        created_via: "manual",
        lifecycle_state: "READY",
        run_status: "RUNNING",
        current_run_id: "run-root",
        current_subtask_id: "subtask-root",
        current_subtask_attempt: 1,
        pause_flag_name: null,
        is_resumable: false,
        authoritative_node_version_id: "node-version-root",
        latest_created_node_version_id: "node-version-root",
        compiled_workflow_id: "workflow-root",
        active_branch_name: "node-root-v1",
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-task-1": {
        node_id: "node-task-1",
        parent_node_id: "node-root",
        kind: "task",
        tier: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell.",
        created_via: "manual",
        lifecycle_state: "COMPLETE",
        run_status: "COMPLETE",
        current_run_id: "run-task-1",
        current_subtask_id: null,
        current_subtask_attempt: null,
        pause_flag_name: null,
        is_resumable: false,
        authoritative_node_version_id: "node-version-task-1",
        latest_created_node_version_id: "node-version-task-1",
        compiled_workflow_id: "workflow-task-1",
        active_branch_name: "node-task-1-v1",
        seed_commit_sha: "def456",
        final_commit_sha: "fedcba",
      },
    },
    nodeLineageByNodeId: {
      "node-root": { logical_node_id: "node-root", authoritative_node_version_id: "node-version-root", latest_created_node_version_id: "node-version-root", versions: [{ id: "node-version-root" }] },
      "node-task-1": { logical_node_id: "node-task-1", authoritative_node_version_id: "node-version-task-1", latest_created_node_version_id: "node-version-task-1", versions: [{ id: "node-version-task-1" }] },
    },
    nodeVersionById: {
      "node-version-root": {
        id: "node-version-root",
        logical_node_id: "node-root",
        parent_node_version_id: null,
        tier: "epic",
        node_kind: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow.",
        description: null,
        status: "authoritative",
        version_number: 1,
        compiled_workflow_id: "workflow-root",
        supersedes_node_version_id: null,
        active_branch_name: "node-root-v1",
        branch_generation_number: 1,
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-version-task-1": {
        id: "node-version-task-1",
        logical_node_id: "node-task-1",
        parent_node_version_id: "node-version-root",
        tier: "task",
        node_kind: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell.",
        description: null,
        status: "authoritative",
        version_number: 1,
        compiled_workflow_id: "workflow-task-1",
        supersedes_node_version_id: null,
        active_branch_name: "node-task-1-v1",
        branch_generation_number: 1,
        seed_commit_sha: "def456",
        final_commit_sha: "fedcba",
      },
    },
    promptHistoryByNodeId: {
      "node-root": {
        node_id: "node-root",
        prompts: [
          {
            id: "prompt-root-1",
            node_version_id: "node-version-root",
            node_run_id: "run-root",
            compiled_subtask_id: "subtask-root",
            prompt_role: "execution",
            source_subtask_key: "research_context",
            template_path: "prompts/root.md",
            template_hash: "hash-root-prompt",
            content: "Investigate the website operator shell requirements.",
            content_hash: "hash-root-prompt-content",
            payload_json: {},
            delivered_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
      "node-task-1": {
        node_id: "node-task-1",
        prompts: [
          {
            id: "prompt-task-1",
            node_version_id: "node-version-task-1",
            node_run_id: "run-task-1",
            compiled_subtask_id: "subtask-task-1",
            prompt_role: "execution",
            source_subtask_key: "execute_node",
            template_path: "prompts/task.md",
            template_hash: "hash-task-prompt",
            content: "Build the first React shell for the operator website.",
            content_hash: "hash-task-prompt-content",
            payload_json: {},
            delivered_at: "2026-03-11T00:00:00Z",
          },
        ],
      },
    },
    supersedeTemplateByNodeId: {
      "node-root": {
        id: "node-version-root-v2",
        logical_node_id: "node-root",
        parent_node_version_id: null,
        tier: "epic",
        node_kind: "epic",
        title: "Website UI bootstrap",
        prompt: "Create the initial website UI workflow with stronger prompt review.",
        description: null,
        status: "candidate",
        version_number: 2,
        compiled_workflow_id: null,
        supersedes_node_version_id: "node-version-root",
        active_branch_name: "node-root-v2",
        branch_generation_number: 2,
        seed_commit_sha: "abc123",
        final_commit_sha: null,
      },
      "node-task-1": {
        id: "node-version-task-1-v2",
        logical_node_id: "node-task-1",
        parent_node_version_id: "node-version-root",
        tier: "task",
        node_kind: "task",
        title: "Bootstrap React shell",
        prompt: "Build the React shell with a real routed detail layout.",
        description: null,
        status: "candidate",
        version_number: 2,
        compiled_workflow_id: null,
        supersedes_node_version_id: "node-version-task-1",
        active_branch_name: "node-task-1-v2",
        branch_generation_number: 2,
        seed_commit_sha: "def456",
        final_commit_sha: null,
      },
    },
    regenerateResponseByNodeId: {
      "node-root": {
        root_node_id: "node-root",
        root_node_version_id: "node-version-root-v2",
        scope: "subtree",
        trigger_reason: "manual_regenerate",
        created_candidate_version_ids: ["node-version-root-v2"],
        stable_candidate_version_ids: ["node-version-root-v2"],
        rebuild_history: [],
      },
      "node-task-1": {
        root_node_id: "node-task-1",
        root_node_version_id: "node-version-task-1-v2",
        scope: "subtree",
        trigger_reason: "manual_regenerate",
        created_candidate_version_ids: ["node-version-task-1-v2"],
        stable_candidate_version_ids: ["node-version-task-1-v2"],
        rebuild_history: [],
      },
    },
    workflowByNodeId: {
      "node-root": {
        id: "workflow-root",
        node_version_id: "node-version-root",
        logical_node_id: "node-root",
        source_hash: "hash-root",
        built_in_library_version: "test",
        created_at: "2026-03-11T00:00:00Z",
        source_document_count: 4,
        task_count: 2,
        subtask_count: 3,
        compile_context: {},
        resolved_yaml: {},
        tasks: [
          { id: "task-a", task_key: "research_context", ordinal: 1, title: "Research", description: null, config_json: {}, subtasks: [{ id: "subtask-a1" }] },
          { id: "task-b", task_key: "execute_node", ordinal: 2, title: "Execute", description: null, config_json: {}, subtasks: [{ id: "subtask-b1" }, { id: "subtask-b2" }] },
        ],
      },
      "node-task-1": {
        id: "workflow-task-1",
        node_version_id: "node-version-task-1",
        logical_node_id: "node-task-1",
        source_hash: "hash-task-1",
        built_in_library_version: "test",
        created_at: "2026-03-11T00:00:00Z",
        source_document_count: 3,
        task_count: 1,
        subtask_count: 1,
        compile_context: {},
        resolved_yaml: {},
        tasks: [{ id: "task-x", task_key: "execute_node", ordinal: 1, title: "Execute", description: null, config_json: {}, subtasks: [{ id: "subtask-x1" }] }],
      },
    },
    runProgressByNodeId: {
      "node-root": { node_id: "node-root", run: { id: "run-root", trigger_reason: "workflow_start" }, current_subtask: { compiled_subtask_id: "subtask-root" }, current_attempt: { attempt_number: 1 } },
      "node-task-1": { node_id: "node-task-1", run: { id: "run-task-1", trigger_reason: "workflow_start" }, current_subtask: null, current_attempt: null },
    },
    runsByNodeId: {
      "node-root": { node_id: "node-root", runs: [{ id: "run-root", status: "RUNNING", trigger_reason: "workflow_start" }] },
      "node-task-1": { node_id: "node-task-1", runs: [{ id: "run-task-1", status: "COMPLETE", trigger_reason: "workflow_start" }] },
    },
    summariesByNodeId: {
      "node-root": { node_id: "node-root", summaries: [{ id: "summary-root", summary_type: "operator", summary_scope: "node", created_at: "2026-03-11T00:00:00Z" }] },
      "node-task-1": { node_id: "node-task-1", summaries: [{ id: "summary-task-1", summary_type: "operator", summary_scope: "node", created_at: "2026-03-11T00:00:00Z" }] },
    },
    sessionsByNodeId: {
      "node-root": { node_id: "node-root", sessions: [{ session_id: "session-root", status: "running", provider: "codex", session_role: "primary", backend: "tmux" }] },
      "node-task-1": { node_id: "node-task-1", sessions: [] },
    },
    sourcesByNodeId: {
      "node-root": { node_version_id: "node-version-root", logical_node_id: "node-root", source_documents: [{ id: "source-root", relative_path: "nodes/epic.yaml", source_role: "base_definition" }] },
      "node-task-1": { node_version_id: "node-version-task-1", logical_node_id: "node-task-1", source_documents: [{ id: "source-task-1", relative_path: "nodes/task.yaml", source_role: "base_definition" }] },
    },
    rationaleByNodeId: {
      "node-root": { node_id: "node-root", node_version_id: "node-version-root", prompt_record_id: null, summary_record_id: null, rationale_summary: "Root node establishes the website UI workstream.", change_counts: { added: 3, modified: 1 }, entity_history: [] },
      "node-task-1": { node_id: "node-task-1", node_version_id: "node-version-task-1", prompt_record_id: null, summary_record_id: null, rationale_summary: "Task node built the initial React shell.", change_counts: { added: 2, modified: 4 }, entity_history: [] },
    },
  },
};

SCENARIOS.empty_project_catalog = {
  id: "empty_project_catalog",
  projectCatalog: {
    daemon_context: {
      reachability_state: "reachable",
      auth_status: "valid",
      daemon_app_name: "AI Coding Daemon",
      daemon_version: "0.1.0",
      authority: "daemon",
      session_backend: "fake",
    },
    projects: [],
  },
  nodeKinds: {
    definitions: [],
    top_level_kinds: [],
  },
  projectBootstrapByProjectId: {},
  topLevelCreateResponseByProjectId: {},
  treeByNodeId: {},
  nodeSummaryByNodeId: {},
  nodeLineageByNodeId: {},
  nodeVersionById: {},
  promptHistoryByNodeId: {},
  supersedeTemplateByNodeId: {},
  regenerateResponseByNodeId: {},
  workflowByNodeId: {},
  runProgressByNodeId: {},
  runsByNodeId: {},
  summariesByNodeId: {},
  sessionsByNodeId: {},
  sourcesByNodeId: {},
  rationaleByNodeId: {},
  actionCatalogByNodeId: {},
};

SCENARIOS.top_level_create_failure = {
  ...structuredClone(SCENARIOS.project_catalog_single),
  id: "top_level_create_failure",
  topLevelCreateErrorByProjectId: {
    repo_alpha: {
      status: 400,
      detail: "mock top-level creation validation failure",
    },
  },
};

SCENARIOS.project_catalog_readiness_problem = {
  ...structuredClone(SCENARIOS.project_catalog_single),
  id: "project_catalog_readiness_problem",
};

SCENARIOS.project_catalog_readiness_problem.projectCatalog.projects = [
  {
    project_id: "repo_alpha",
    label: "repo_alpha",
    source_path: "repos/repo_alpha",
    bootstrap_ready: true,
    readiness_code: "ready",
    readiness_message: null,
    default_branch: "main",
    head_commit_sha: "abc1234def56",
  },
  {
    project_id: "repo_broken",
    label: "repo_broken",
    source_path: "repos/repo_broken",
    bootstrap_ready: false,
    readiness_code: "not_git_repo",
    readiness_message: "Directory is not a git repository.",
    default_branch: null,
    head_commit_sha: null,
  },
];
SCENARIOS.project_catalog_readiness_problem.projectBootstrapByProjectId = {
  repo_alpha: structuredClone(SCENARIOS.project_catalog_single.projectBootstrapByProjectId.repo_alpha),
  repo_broken: {
    project: {
      project_id: "repo_broken",
      label: "repo_broken",
      source_path: "repos/repo_broken",
      bootstrap_ready: false,
      readiness_code: "not_git_repo",
      readiness_message: "Directory is not a git repository.",
      default_branch: null,
      head_commit_sha: null,
    },
    root_node_id: null,
    route_hint: null,
  },
};

SCENARIOS.prompt_candidate_blocked = {
  ...structuredClone(SCENARIOS.healthy_tree_small),
  id: "prompt_candidate_blocked",
};

SCENARIOS.tree_filter_matrix = {
  ...structuredClone(SCENARIOS.healthy_tree_small),
  id: "tree_filter_matrix",
};

SCENARIOS.tree_filter_matrix.treeByNodeId["node-root"] = {
  root_node_id: "node-root",
  generated_at: "2026-03-11T00:00:00Z",
  nodes: [
    {
      node_id: "node-root",
      parent_node_id: null,
      depth: 0,
      kind: "epic",
      tier: "epic",
      title: "Website UI bootstrap",
      authoritative_node_version_id: "node-version-root",
      latest_created_node_version_id: "node-version-root",
      lifecycle_state: "READY",
      run_status: "RUNNING",
      scheduling_status: "already_running",
      blocker_count: 0,
      blocker_state: "none",
      has_children: true,
      child_count: 4,
      child_rollups: {
        total: 4,
        ready: 1,
        running: 0,
        paused_for_user: 1,
        blocked: 1,
        failed: 0,
        complete: 1,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-phase-1",
      parent_node_id: "node-root",
      depth: 1,
      kind: "phase",
      tier: "phase",
      title: "Phase waiting on children",
      authoritative_node_version_id: "node-version-phase-1",
      latest_created_node_version_id: "node-version-phase-1",
      lifecycle_state: "READY",
      run_status: null,
      scheduling_status: "blocked",
      blocker_count: 2,
      blocker_state: "blocked",
      has_children: true,
      child_count: 1,
      child_rollups: {
        total: 1,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 1,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-plan-1",
      parent_node_id: "node-root",
      depth: 1,
      kind: "plan",
      tier: "plan",
      title: "Plan waiting on user input",
      authoritative_node_version_id: "node-version-plan-1",
      latest_created_node_version_id: "node-version-plan-1",
      lifecycle_state: "PAUSED_FOR_USER",
      run_status: "PAUSED",
      scheduling_status: "paused_for_user",
      blocker_count: 0,
      blocker_state: "paused_for_user",
      has_children: false,
      child_count: 0,
      child_rollups: {
        total: 0,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 0,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-task-1",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Bootstrap React shell",
      authoritative_node_version_id: "node-version-task-1",
      latest_created_node_version_id: "node-version-task-1",
      lifecycle_state: "COMPLETE",
      run_status: "COMPLETE",
      scheduling_status: "complete",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: {
        total: 0,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 0,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
    {
      node_id: "node-task-2",
      parent_node_id: "node-root",
      depth: 1,
      kind: "task",
      tier: "task",
      title: "Implement active sidebar filters",
      authoritative_node_version_id: "node-version-task-2",
      latest_created_node_version_id: "node-version-task-2",
      lifecycle_state: "RUNNING",
      run_status: "RUNNING",
      scheduling_status: "already_running",
      blocker_count: 0,
      blocker_state: "none",
      has_children: false,
      child_count: 0,
      child_rollups: {
        total: 0,
        ready: 0,
        running: 0,
        paused_for_user: 0,
        blocked: 0,
        failed: 0,
        complete: 0,
        superseded: 0,
        not_compiled: 0,
      },
      created_at: "2026-03-11T00:00:00Z",
      last_updated_at: "2026-03-11T00:00:00Z",
    },
  ],
};

SCENARIOS.prompt_candidate_blocked.nodeLineageByNodeId["node-task-1"] = {
  logical_node_id: "node-task-1",
  authoritative_node_version_id: "node-version-task-1",
  latest_created_node_version_id: "node-version-task-1-v2",
  versions: [{ id: "node-version-task-1" }, { id: "node-version-task-1-v2" }],
};

SCENARIOS.prompt_candidate_blocked.nodeVersionById["node-version-task-1-v2"] = {
  id: "node-version-task-1-v2",
  logical_node_id: "node-task-1",
  parent_node_version_id: "node-version-root",
  tier: "task",
  node_kind: "task",
  title: "Bootstrap React shell",
  prompt: "Build the React shell with a real routed detail layout.",
  description: null,
  status: "candidate",
  version_number: 2,
  compiled_workflow_id: null,
  supersedes_node_version_id: "node-version-task-1",
  active_branch_name: "node-task-1-v2",
  branch_generation_number: 2,
  seed_commit_sha: "def456",
  final_commit_sha: null,
};

SCENARIOS.prompt_candidate_blocked.nodeSummaryByNodeId["node-task-1"] = {
  ...SCENARIOS.prompt_candidate_blocked.nodeSummaryByNodeId["node-task-1"],
  latest_created_node_version_id: "node-version-task-1-v2",
};

SCENARIOS.prompt_candidate_blocked.treeByNodeId["node-root"].nodes = SCENARIOS.prompt_candidate_blocked.treeByNodeId["node-root"].nodes.map((node) =>
  node.node_id === "node-task-1"
    ? {
        ...node,
        latest_created_node_version_id: "node-version-task-1-v2",
      }
    : node,
);
